### ISSUE TITLE
What happens when dates are the same?

### ISSUE THREAD

**Issue by sffc** [fabalbon/proposal-intl-DateTimeFormat-formatRange#4]
We discussed in ECMA 402 and Issue #1 that there seems to be a desire to allow dates to be given to the API in either order.

What happens if the dates are the same?

I think this should not be an exception, because if we are friendly about the order in which you provide dates, it feels unexpected that we would throw an exception just in this one case.

A few options:

1. Fall back to a non-range format
2. Display the range naively, as in "July 20 - 20, 2018"
3. Use an approximation pattern, as in "July ~20, 2018"

This question also came up in the context of currency range formatting.  The solution over in that space is not locked in yet.  The decision here might set a precedent for how to deal with this problem in range formatting APIs in general.

**Comment by fabalbon** [comment]
The three options look interesting. I think that instead of simply using one fallback mechanism, we could potentially give users the possibility to choose which one they want to use.

**Option 1)**
TR-35 already uses this as the [fallback](https://unicode.org/reports/tr35/tr35-dates.html#intervalFormats) when the two dates are the same: If all calendar fields that are being displayed are common between the two dates (e.g. equal or sufficiently similar dates), the dates will be formatted using the regular date/time format.

This is the fallback that's being used on the current draft of the spec text.

**Option 2)**
In this case, the date interval should be formatted using the interval pattern for the smallest calendar field and not the regular date/time pattern (as in option 1).

For example, we have these interval patterns:
`y: 'MMM dd, y - MMM dd, y'`
`M: 'MMM dd - MMM dd, y'`
`d: 'MMM dd - dd, y'`

If both date's `y`, `M` and `d` are equal, then the `d` pattern should be used. 

**Option 3)**
Supporting this fallback will require implementers to add additional localized pattern data (the previous two options can be implemented using the data that is already there).

We should explore this option, but I think we should add it only if we see an actual need for an approximation pattern.

**Comment by fabalbon** [comment]
We discussed this in the August 2018 Ecma402 monthly call and we agreed to only support Option 1 on the initial version of this proposal. 

We could support Option 2 (with option 1 being the default) on a second version.

**Comment by fabalbon** [comment]
Closing this issue for now. We can reopen once we decide to explore options 2 or 3.

**Comment by leobalter** [comment]
I'm +1 to keep it as Option 1. 

> We could support Option 2 (with option 1 being the default) on a second version.

I don't think this should ever block this current proposal.
