### ISSUE TITLE
Weekday should be included in Table 2 #table-datetimeformat-rangepatternfields

### ISSUE THREAD

**Issue by FrankYFTang** [fabalbon/proposal-intl-DateTimeFormat-formatRange#7]
Somehow Table 2 Range pattern fields
currently does not include "weekday"

https://rawgit.com/fabalbon/proposal-intl-DateTimeFormat-formatRange/master/out/#table-datetimeformat-rangepatternfields

I think "weekday" should be included in here.

**Comment by fabalbon** [comment]
Weekday is different to the rest of the calendar fields on that list in the sense that it is not used when describing a specific point in time, but instead it is additional information that you can display for a date. 

The data and the algorithm that picks the best interval pattern assumes that for a specific value of a calendar field, the values of the calendar field that is immediately smaller will never repeat. This is the case between `month` and `day`, but the value of `weekday` will repeat in a single `month`. This causes an unexpected behavior because the same `weekday` on a month might or might not refer to the same day.

CLDR does not include date interval patterns for `weekday` and implementations, such as ICU, do not use `weekday` when calculating the largest different calendar field.

This does not mean that `weekday` cannot be displayed when formatting date intervals. If your skeleton has `weekday` then it will be displayed, but `weekday` won't be used to pick the interval pattern.

**Comment by FrankYFTang** [comment]
ok, I see.
